//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module game(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
   wire p1_hit_by_p2, p2_hit_by_p1;
	wire game_over_signal, p1_wins, p2_wins;
	wire [1:0] p1_health, p1_block_points;
   wire [1:0] p2_health, p2_block_points;
	 
	reg menu_mode = 1;
	reg countdown_mode = 0;
	reg game_mode = 0;
	reg selected_mode;
	reg game_over_mode = 0;
	
	reg [25:0] key_debounce_counter = 0;
	parameter KEY_DEBOUNCE_DELAY = 2_500_000; 
	reg key_pressed_prev = 0;
	wire any_key_pressed = ~KEY[3] || ~KEY[2] || ~KEY[1] || ~KEY[0];
	
	
	reg [1:0] countdown_value = 2'b11; // 3, 2, 1 (11, 10, 01)
	reg [25:0] countdown_counter = 0;
	parameter COUNTDOWN_DELAY = 50_000_000; 
	
	reg [6:0] game_counter = 0;  // 0 to 99
	reg [25:0] counter_clock = 0;
	
	reg transitioning_from_game_over = 0;
	
	
	//main selection logic between game modes
	always @(posedge CLOCK_50) begin
    key_pressed_prev <= any_key_pressed;
    
    if (SW[9]) begin //SW9:reset(active high)
        menu_mode <= 1;
        countdown_mode <= 0;
        game_mode <= 0;
        game_over_mode <= 0;
        countdown_value <= 2'b11;
        countdown_counter <= 0;
        counter_clock <= 0;
        key_debounce_counter <= 0;
        transitioning_from_game_over <= 0;
    end
    else if (menu_mode) begin
        transitioning_from_game_over <= 0;
        
        if (SW[0]) selected_mode <= 1; // PVP
        else       selected_mode <= 0; // PVE
        
        if (any_key_pressed && !key_pressed_prev && !transitioning_from_game_over) begin
            menu_mode <= 0;
            countdown_mode <= 1;
            countdown_value <= 2'b11;
            countdown_counter <= 0;
        end
    end
    else if (countdown_mode) begin
        if (countdown_counter >= COUNTDOWN_DELAY - 1) begin
            countdown_counter <= 0;
            if (countdown_value == 2'b00) begin // after go,game mode
                countdown_mode <= 0;
                game_mode <= 1;
            end
            else begin
                countdown_value <= countdown_value - 1;
            end
        end
        else begin
            countdown_counter <= countdown_counter + 1;
        end
    end
    else if (game_mode) begin
        if (game_over_signal) begin
            game_mode <= 0;
            game_over_mode <= 1;
            key_debounce_counter <= 0;
        end
        else if (game_counter >= 99) begin
            game_mode <= 0;
            game_over_mode <= 1;
            key_debounce_counter <= 0;
        end
    end  
    else if (game_over_mode) begin  
        if (key_debounce_counter >= KEY_DEBOUNCE_DELAY) begin
            if (any_key_pressed && !key_pressed_prev) begin
                game_over_mode <= 0;
                menu_mode <= 1;
                countdown_mode <= 0;
                game_mode <= 0;
                countdown_value <= 2'b11;
                countdown_counter <= 0;
                counter_clock <= 0;
                selected_mode <= 0;
                key_debounce_counter <= 0;
                transitioning_from_game_over <= 1;
            end
        end
        else begin
            key_debounce_counter <= key_debounce_counter + 1;
        end
    end
end


// Clocks
    wire clk_25mhz;
    wire clk_60hz;
    assign game_clk = (SW[1] == 1'b0) ? clk_60hz : ~KEY[0];


	 
	 clk_divider #(.DIV(833_333)) game_clk_div (
    .clk(CLOCK_50),
    .clk_out(clk_60hz)
);


	clk_divider #(.DIV(2)) vga_clk_div (
    .clk(CLOCK_50),
    .clk_out(clk_25mhz)
);

//counters(w.r.t. game clock and key clock)
reg [5:0] game_tick_counter = 0;
always @(posedge game_clk or posedge reset) begin
    if (reset) begin
        game_tick_counter <= 0;
        game_counter <= 0;
    end else if (game_mode) begin
        if (game_tick_counter >= 59) begin // 60 ticks = 1 second
            game_tick_counter <= 0;
            if (game_counter < 99) begin
                game_counter <= game_counter + 1;
            end
        end else begin
            game_tick_counter <= game_tick_counter + 1;
        end
    end else begin
        game_tick_counter <= 0;
    end
end
	
	

//game over display
wire [7:0] game_over_vga_color;
wire game_over_vga_active;
game_over_display  game_overcik (
    .vga_x(next_x),
    .vga_y(next_y),
    .p1_wins(p1_wins),
    .p2_wins(p2_wins),
    .match_duration(game_counter),
    .game_over_color(game_over_vga_color),
    .game_over_active(game_over_vga_active)
);

// health and block bar displays
wire [7:0] health_block_bar_color;
wire health_block_bar_active;
health_block_bars  bars(
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .p1_health(p1_health),
    .p1_block_points(p1_block_points),
    .p2_health(p2_health),
    .p2_block_points(p2_block_points),
    .bar_color(health_block_bar_color),
    .bar_active(health_block_bar_active)
);
	
//countdown display on vga
reg [3:0] countdown_hex;
	always @(*) begin
		case (countdown_value)
			2'b11: countdown_hex = 4'd3; // 3
			2'b10: countdown_hex = 4'd2; // 2
			2'b01: countdown_hex = 4'd1; // 1
			2'b00: countdown_hex = 4'd0; // GO
			default: countdown_hex = 4'd0; // 0 (blank)
		endcase
	end
	
	
	//menu display on vga
wire [7:0] menu_bg_color;
menu_background menu_bg (
		.x(next_x),
		.y(next_y),
		.color_out(menu_bg_color)
);

wire in_box_pvp = (next_x >= 165 && next_x < 185 &&
	                    next_y >= 180 && next_y < 200);

wire in_box_pve = (next_x >= 165 && next_x < 185 &&
	                    next_y >= 330 && next_y < 350);

wire [7:0] box_pvp_color = selected_mode ? 8'b11100000 : 8'b00011100;
wire [7:0] box_pve_color = !selected_mode ? 8'b11100000 : 8'b00011100;

	 assign reset = SW[9];
	 assign VGA_BLANK_N = 1'b1;
	 assign VGA_SYNC_N  = 1'b1;
	 assign VGA_CLK     = CLOCK_50;


    // VGA Driver
    wire [9:0] next_x, next_y;
    reg [7:0] color;

    vga_driver vga (
        .clock(clk_25mhz),
        .reset(reset),
        .color_in(color),
        .next_x(next_x),
        .next_y(next_y),
        .hsync(VGA_HS),
        .vsync(VGA_VS),
        .red(VGA_R),
        .green(VGA_G),
        .blue(VGA_B)
    );
 
	 
	// Character positions
	parameter CHAR_WIDTH  = 64;
	parameter CHAR_HEIGHT = 120;
	parameter CHAR_Y      = 280;

	parameter CHAR2_WIDTH  = 64;
	parameter CHAR2_HEIGHT = 120;
	parameter CHAR2_Y      = 280;
	parameter CHAR2_X      = 576;
	
	//FSM Reset 
	wire fsm_reset;
	assign fsm_reset = SW[9] || (countdown_mode && countdown_value == 2'b11 && countdown_counter == 0);

    // FSM
    wire [9:0] ryu;
    wire [3:0] ryu_state;

player_fsm fsm (
        .reset(fsm_reset),
        .sw1(SW[1]),
        .clk_60hz(clk_60hz),
        .manual_step(game_mode ? ~KEY[0] : 1'b1),
        .move_left(game_mode ? ~KEY[2] : 1'b0),
        .move_right(game_mode ? ~KEY[1] : 1'b0),
        .attack(game_mode ? ~KEY[3] : 1'b0),
		  .hit_by_opponent(p1_hit_by_p2),
		  .blocked_opponent(1'b0),
		  .opponent_x(ken),
        .player(ryu),
        .state(ryu_state),
		  .health(p1_health),
		  .block_points(p1_block_points)
);
	 
	wire [13:0] sprite_addr = (next_y - CHAR_Y) * CHAR_WIDTH + (next_x - ryu);

	//Player 2 FSM 
	wire [9:0] ken;
	wire [3:0] ken_state;
	
	// Bot FSM  
	wire bot_move_left, bot_move_right, bot_attack;
	wire [9:0] bot_player_pos;
	wire [3:0] bot_state; 
	wire [1:0] bot_health, bot_block_points;
	
	bot_fsm ken_bot (
    .reset(fsm_reset),
    .sw1(SW[1]),
    .clk_60hz(clk_60hz),
    .manual_step(game_mode ? ~KEY[0] : 1'b1),
    .hit_by_opponent(p2_hit_by_p1),
    .blocked_opponent(1'b0),
	 .opponent_x(ryu),
    .move_left(bot_move_left),
    .move_right(bot_move_right),
    .attack(bot_attack),
    .player(bot_player_pos),
    .state(bot_state),
    .health(bot_health),
    .block_points(bot_block_points)
);

	wire ken_move_left  = game_mode ? ((selected_mode == 0) ? bot_move_left  : SW[6]) : 1'b0;
	wire ken_move_right = game_mode ? ((selected_mode == 0) ? bot_move_right : SW[4]) : 1'b0;
	wire ken_attack     = game_mode ? ((selected_mode == 0) ? bot_attack     : SW[5]) : 1'b0;

	player2_fsm ken_fsm (
    .reset(fsm_reset),
    .sw1(SW[1]),
    .clk_60hz(clk_60hz),
    .manual_step(game_mode ? ~KEY[0] : 1'b1),
    .move_left(ken_move_left),
	 .move_right(ken_move_right),
	 .attack(ken_attack),
	 .hit_by_opponent(p2_hit_by_p1),
	 .blocked_opponent(1'b0),
	 .opponent_x(ryu),
    .player(ken),
    .state(ken_state),
	 .health(p2_health),
    .block_points(p2_block_points)
);

	wire timer_limit_reached;
	assign timer_limit_reached = (game_counter >= 99);
	
	hit_detection hit_detectcik (
    .clk(CLOCK_50),
    .reset(reset),
    .p1_x(ryu),
    .p1_state(ryu_state),
    .p1_health(p1_health),
    .p2_x(ken),
    .p2_state(ken_state),
    .p2_health(p2_health),
	 .timer_limit_reached(timer_limit_reached),
    .p1_hit_by_p2(p1_hit_by_p2),
    .p2_hit_by_p1(p2_hit_by_p1),
    .game_over(game_over_signal),
    .p1_wins(p1_wins),
    .p2_wins(p2_wins)
);



	//countdown display
	wire in_countdown_area = (next_x >= 300 && next_x < 340 && 
	                         next_y >= 200 && next_y < 240);
	//digits(321 bitir isi)
	wire [7:0] countdown_display_color;
	countdown_display countdown_disp (
		.x(next_x),
		.y(next_y),
		.countdown_value(countdown_value),
		.color_out(countdown_display_color),
		.in_digit_area(in_countdown_area)
	);
	
	//counter display
	wire in_counter_area = (next_x >= 280 && next_x < 360 && 
                       next_y >= 20 && next_y < 60);
	//digits (00 to 99)						  
	wire [7:0] counter_display_color;
	counter_display counter_disp (
    .x(next_x),
    .y(next_y),
    .counter_value(game_counter),
    .color_out(counter_display_color),
    .in_counter_area(in_counter_area)
);

 
	// Player 1 (Ryu) attack states
	wire is_ryu_attack = (ryu_state == 4'b0100);
	wire is_ryu_dir_attack = (ryu_state == 4'b0111);
	wire is_ryu_hitstun = (ryu_state == 4'b1001);
	wire is_ryu_blockstun = (ryu_state == 4'b1010);
	wire is_ryu_lose = (ryu_state == 4'b1011);
	wire is_ryu_blocking = (ryu_state == 4'b1010);
	
	wire is_ryu_hitstun_visual = is_ryu_hitstun;
	wire is_ryu_blockstun_visual = is_ryu_blockstun;
	wire is_ryu_lose_visual = is_ryu_lose;
	wire is_ryu_attacking_visual = (ryu_state == 4'b0011 || ryu_state == 4'b0100 || ryu_state == 4'b0101);
	wire is_ryu_dir_attacking_visual = (ryu_state == 4'b0110 || ryu_state == 4'b0111 || ryu_state == 4'b1000);

	// Player 2 (Ken) attack states
	wire is_ken_attack = (ken_state == 4'b0100);
	wire is_ken_dir_attack = (ken_state == 4'b0111);
	wire is_ken_hitstun = (ken_state == 4'b1001);
	wire is_ken_blockstun = (ken_state == 4'b1010);
	wire is_ken_lose = (ken_state ==4'b1011);
	wire is_ken_blocking = (ken_state == 4'b1010);
	
	
	wire is_ken_attacking_visual = (ken_state == 4'b0011 || ken_state == 4'b0100 || ken_state == 4'b0101);
	wire is_ken_dir_attacking_visual = (ken_state == 4'b0110 || ken_state == 4'b0111 || ken_state == 4'b1000);
	wire is_ken_hitstun_visual = is_ken_hitstun;
	wire is_ken_blockstun_visual = is_ken_blockstun;
	wire is_ken_lose_visual = is_ken_lose;
	
	// Ryu sprite rendering
	wire [7:0] sprite_color_idle, sprite_color_attack, sprite_color_dir_attack;
	wire[7:0] sprite_color_hitstun,sprite_color_blockstun,sprite_color_lose;
	
	wire sprite_valid_idle, sprite_valid_attack, sprite_valid_dir_attack;
	wire sprite_valid_hitstun, sprite_valid_blockstun , sprite_valid_lose;
	
	//sprite instantiations 
	character_render ryu_idle (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ryu),
    .sprite_y(CHAR_Y),
	 .sprite_select(4'b0000),
    .pixel_data(sprite_color_idle),
    .pixel_on(sprite_valid_idle)
);

	character_render ryu_attack (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ryu),
    .sprite_y(CHAR_Y),
	 .sprite_select(4'b0001),
    .pixel_data(sprite_color_attack),
    .pixel_on(sprite_valid_attack)
);
	
	character_render ryu_dir_attack (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ryu),
    .sprite_y(CHAR_Y),
	 .sprite_select(4'b0011),
    .pixel_data(sprite_color_dir_attack),
    .pixel_on(sprite_valid_dir_attack)
);
	character_render ryu_hitstun (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ryu),
    .sprite_y(CHAR_Y),
    .sprite_select(4'b0100), 
    .pixel_data(sprite_color_hitstun),
    .pixel_on(sprite_valid_hitstun)
);
	character_render ryu_blockstun (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ryu),
    .sprite_y(CHAR_Y),
    .sprite_select(4'b0010), 
    .pixel_data(sprite_color_blockstun),
    .pixel_on(sprite_valid_blockstun)
);
	character_render ryu_lose (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ryu),
    .sprite_y(CHAR_Y),
    .sprite_select(4'b0101), 
    .pixel_data(sprite_color_lose),
    .pixel_on(sprite_valid_lose)
);

	//Ken sprite rendering
	wire [13:0] sprite2_addr = (next_y - CHAR2_Y) * CHAR2_WIDTH + (next_x - ken);

	wire [7:0] sprite2_color_idle, sprite2_color_attack, sprite2_color_dir_attack;
	wire [7:0] sprite2_color_hitstun, sprite2_color_blockstun,sprite2_color_lose;
	
	wire sprite2_valid_idle, sprite2_valid_attack, sprite2_valid_dir_attack;
	wire sprite2_valid_hitstun, sprite2_valid_blockstun , sprite2_valid_lose;


	character_render ken_idle (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ken),
    .sprite_y(CHAR2_Y),
	 .sprite_select(4'b1000),
    .pixel_data(sprite2_color_idle),
    .pixel_on(sprite2_valid_idle)
);

	character_render ken_attack_inst (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ken),
    .sprite_y(CHAR2_Y),
	 .sprite_select(4'b1001),
    .pixel_data(sprite2_color_attack),
    .pixel_on(sprite2_valid_attack)
);

	character_render ken_dir_attack (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ken),
    .sprite_y(CHAR2_Y),
	 .sprite_select(4'b1011),
    .pixel_data(sprite2_color_dir_attack),
    .pixel_on(sprite2_valid_dir_attack)
);
	character_render ken_hitstun (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ken),
    .sprite_y(CHAR2_Y),
    .sprite_select(4'b1100), 
    .pixel_data(sprite2_color_hitstun),
    .pixel_on(sprite2_valid_hitstun)
);
	character_render ken_blockstun (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ken),
    .sprite_y(CHAR2_Y),
    .sprite_select(4'b1010), 
    .pixel_data(sprite2_color_blockstun),
    .pixel_on(sprite2_valid_blockstun)
);

	wire in_char2_box =
		(next_x >= ken && next_x < ken + CHAR2_WIDTH &&
      next_y >= CHAR2_Y && next_y < CHAR2_Y + CHAR2_HEIGHT);

	// Background
	wire [7:0] bg_color;
	background background_inst (
    .x(next_x),
    .y(next_y),
    .color_out(bg_color)
);
	character_render ken_lose (
    .clk(clk_25mhz),
    .vga_x(next_x),
    .vga_y(next_y),
    .sprite_x(ken),
    .sprite_y(CHAR2_Y),
    .sprite_select(4'b1101), 
    .pixel_data(sprite2_color_lose),
    .pixel_on(sprite2_valid_lose)
);

	parameter HURTBOX_FILL = 8'b00000001;
	parameter HITBOX_FILL  = 8'b10000000;
	wire show_hurtboxes = (SW[1] == 1'b1);

	// RYU hurtbox
	wire in_ryu_hurtbox = 
		(next_x >= ryu + 8 && next_x < ryu + CHAR_WIDTH - 8 &&
		next_y >= CHAR_Y + 4 && next_y < CHAR_Y + CHAR_HEIGHT - 4);

	// RYU hitbox (normal attack)
	wire show_ryu_hitbox = is_ryu_attack;
	wire in_ryu_hitbox =
		(next_x >= ryu + CHAR_WIDTH*2/3 && next_x < ryu + CHAR_WIDTH + 20 &&
      next_y >= CHAR_Y + 24 && next_y < CHAR_Y + 60);
		
	//RYU directional hitbox
	wire show_ryu_dir_hitbox = is_ryu_dir_attack;	
	wire in_ryu_dir_hitbox = 
    (next_x >= ryu + CHAR_WIDTH*2/3 && next_x < ryu + CHAR_WIDTH + 15 &&     
     next_y >= CHAR_Y + 30 && next_y < CHAR_Y + 65); 

	//KEN hurtbox
	wire in_ken_hurtbox =
    (next_x >= ken + 8 && next_x < ken + CHAR_WIDTH - 8 &&
    next_y >= CHAR2_Y + 4 && next_y < CHAR2_Y + CHAR_HEIGHT - 4);
	 
	//KEN hitbox (normal attack) 
	wire show_ken_hitbox = is_ken_attack;
	wire in_ken_hitbox =
    (next_x >= ken - 10 && next_x < ken + CHAR_WIDTH*2/3 &&  
    next_y >= CHAR2_Y + 24 && next_y < CHAR2_Y + 60);
		
	//KEN directional hitbox 
	wire show_ken_dir_hitbox = is_ken_dir_attack;
	wire in_ken_dir_hitbox = 
   (next_x >= ken - 15 && next_x < ken + CHAR_WIDTH/3 &&
   next_y >= CHAR2_Y + 30 && next_y < CHAR2_Y + 65);
	
	//COLORING
always @(*) begin
    color = bg_color;
    
    // priority
    if (menu_mode) begin
        if (in_box_pvp) begin
            color = box_pvp_color;
        end else if (in_box_pve) begin
            color = box_pve_color;
        end else begin
            color = menu_bg_color;
        end
    end
	 
    else if (countdown_mode) begin
        if (in_countdown_area) begin
            color = countdown_display_color;
        end else begin
            color = bg_color;
        end
    end
	 
    else if (game_over_mode) begin
        color = game_over_vga_color;
    end

    else begin
        if (health_block_bar_active) begin
            color = health_block_bar_color;
        end
        
        else if (in_counter_area) begin
            color = counter_display_color;
        end
        
        else if ((show_ryu_hitbox && in_ryu_hitbox) || 
                 (show_ryu_dir_hitbox && in_ryu_dir_hitbox) || 
                 (show_ken_hitbox && in_ken_hitbox) || 
                 (show_ken_dir_hitbox && in_ken_dir_hitbox)) begin
            color = HITBOX_FILL;
        end
        
        // P1 sprites
        else if (next_x >= ryu && next_x < ryu + CHAR_WIDTH &&
                 next_y >= CHAR_Y && next_y < CHAR_Y + CHAR_HEIGHT) begin
            
            if (is_ryu_hitstun_visual && sprite_valid_hitstun) begin
                color = sprite_color_hitstun;
            end else if (is_ryu_lose_visual && sprite_valid_lose) begin
                color = sprite_color_lose;
            end else if (is_ryu_blocking && sprite_valid_blockstun) begin
                color = sprite_color_blockstun;
            end else if (is_ryu_dir_attacking_visual && sprite_valid_dir_attack && 
                        sprite_color_dir_attack != 8'b00000000) begin
                color = sprite_color_dir_attack;
            end else if (is_ryu_dir_attacking_visual && show_hurtboxes && in_ryu_hurtbox) begin
                color = HURTBOX_FILL;  // hurtbox only in  key
            end else if (is_ryu_attacking_visual && sprite_valid_attack) begin
                color = sprite_color_attack;
            end else if (!is_ryu_attacking_visual && !is_ryu_dir_attacking_visual && 
                        !is_ryu_hitstun_visual && !is_ryu_blocking && 
                        !is_ryu_lose_visual && sprite_valid_idle) begin
                color = sprite_color_idle;
            end else if (show_hurtboxes && in_ryu_hurtbox) begin
                color = HURTBOX_FILL;  //  hurtbox only  in key 
            end else begin
                color = bg_color;
            end
        end
        
        // P2
        else if (next_x >= ken && next_x < ken + CHAR_WIDTH &&
                 next_y >= CHAR2_Y && next_y < CHAR2_Y + CHAR_HEIGHT) begin
            
            if (is_ken_hitstun_visual && sprite2_valid_hitstun) begin
                color = sprite2_color_hitstun;
            end else if (is_ken_lose_visual && sprite2_valid_lose) begin
                color = sprite2_color_lose;
            end else if (is_ken_blocking && sprite2_valid_blockstun) begin
                color = sprite2_color_blockstun;
            end else if (is_ken_dir_attacking_visual && sprite2_valid_dir_attack && 
                        sprite2_color_dir_attack != 8'b00000000) begin
                color = sprite2_color_dir_attack;
            end else if (is_ken_dir_attacking_visual && show_hurtboxes && in_ken_hurtbox) begin
                color = HURTBOX_FILL;  // hurtbox only in  key
            end else if (is_ken_attacking_visual && sprite2_valid_attack) begin
                color = sprite2_color_attack;
            end else if (!is_ken_attacking_visual && !is_ken_dir_attacking_visual && 
                        !is_ken_hitstun_visual && !is_ken_blocking && 
                        !is_ken_lose_visual && sprite2_valid_idle) begin
                color = sprite2_color_idle;
            end else if (show_hurtboxes && in_ken_hurtbox) begin
                color = HURTBOX_FILL;  //  hurtbox only  in key
            end else begin
                color = bg_color;
            end
        end
        
        else if ((is_ryu_dir_attacking_visual || is_ken_dir_attacking_visual) && 
                 show_hurtboxes && (in_ryu_hurtbox || in_ken_hurtbox)) begin
            color = HURTBOX_FILL;
        end
        
        else if (show_hurtboxes && (in_ryu_hurtbox || in_ken_hurtbox)) begin
            color = HURTBOX_FILL;
        end
        
        else begin
            color = bg_color;
        end
    end
end
	 
	 
reg [24:0] blink_counter = 0;
reg blink_state = 0;
parameter BLINK_DELAY = 25_000_000;

//blink counter for game over  
always @(posedge CLOCK_50) begin
    if (game_over_mode) begin
        if (blink_counter >= BLINK_DELAY - 1) begin
            blink_counter <= 0;
            blink_state <= ~blink_state;
        end else begin
            blink_counter <= blink_counter + 1;
        end
    end else begin
        blink_counter <= 0;
        blink_state <= 1; 
    end
end

wire [6:0] countdown_7seg;
	hexto7seg countdown_display_hex (
		.hexn(countdown_7seg),
		.hex(countdown_hex)
	);
	

assign LEDR[9:7] = menu_mode ? 3'b000 :  //  menu,off
                   game_over_mode ? (blink_state ? 3'b111 : 3'b000) : // game over,blink all 
                   (p1_health == 3) ? 3'b111 :   //3 health
                   (p1_health == 2) ? 3'b110 :    //2 health
                   (p1_health == 1) ? 3'b100 :    //1 health
                   3'b000; 
assign LEDR[2:0] = menu_mode ? 3'b000 :  // menu, off
                   game_over_mode ? (blink_state ? 3'b111 : 3'b000) : // game over, blink all 
                   (p2_health == 3) ? 3'b111 :   // P2: 3 health 
                   (p2_health == 2) ? 3'b110 :   // P2: 2 health 
                   (p2_health == 1) ? 3'b100 :   // P2: 1 health 
                   3'b000;                         
						 
assign LEDR[6:3] = menu_mode ? 4'b0000 :  //menu,off  
                   game_over_mode ? (blink_state ? 4'b1111 : 4'b0000) : // game over,blink all
                   4'b0000;
	
	
	wire [3:0] tens_digit = (game_counter >= 10) ? game_counter / 10 : 4'd0;
	wire [3:0] ones_digit = game_counter % 10;

	wire [6:0] tens_7seg, ones_7seg;
	wire [6:0] num_1, num_2;


	wire is_draw;
	assign is_draw = timer_limit_reached || ((p1_health == 0) && (p2_health == 0));
	
	wire [6:0] char_P = 7'b0001100;     // P
	wire [6:0] char_E = 7'b0000110;     // E  
	wire [6:0] char_q = 7'b0011000;     // q
	wire [6:0] char_dash = 7'b0111111;  // -
	wire [6:0] char_F = 7'b0001110;     // F
	wire [6:0] char_I = 7'b1001111;     // I
	wire [6:0] char_G = 7'b1000010;     // G
	wire [6:0] char_H = 7'b0001001;     // H
	wire [6:0] char_T = 7'b0000111;     // t
	wire [6:0] char_O = 7'b1000000;     // O
	
	hexto7seg tens_converter (.hexn(tens_7seg),.hex(tens_digit));
	hexto7seg ones_converter (.hexn(ones_7seg),.hex(ones_digit)); 
	hexto7seg num_1_converter (.hexn(num_1),.hex(4'd1));
	hexto7seg num_2_converter (.hexn(num_2),.hex(4'd2));

	//hex assignments for overall game logic
assign HEX0 = (menu_mode) ? 7'h7F :                    
              (countdown_mode) ? (countdown_value == 2'b00 ? char_O : countdown_7seg) :  
              (game_mode) ? 7'h7F :                    
              (game_over_mode) ? char_dash : 7'h7F;    

assign HEX1 = (menu_mode) ? 7'h7F :                    
              (countdown_mode) ? 7'h7F :               
              (game_mode) ? char_T :                   
              (game_over_mode) ? ones_7seg : 7'h7F;    

assign HEX2 = (menu_mode) ? 7'h7F :                    
              (countdown_mode) ? 7'h7F :                
              (game_mode) ? char_H :                   
              (game_over_mode) ? tens_7seg : 7'h7F;    

assign HEX3 = (menu_mode) ? 7'h7F :                    
              (countdown_mode) ? 7'h7F :               
              (game_mode) ? char_G :                   
              (game_over_mode) ? char_dash : 7'h7F;    

assign HEX4 = (menu_mode) ? char_P :                   
              (countdown_mode) ? 7'h7F :               
              (game_mode) ? char_I :                   
              (game_over_mode) ? (
                  p1_wins ? num_1 :                    
                  p2_wins ? num_2 :                    
                  char_q                               
              ) : 7'h7F;

assign HEX5 = (menu_mode) ? (selected_mode ? num_2 : num_1) :  
              (countdown_mode) ? 7'h7F :               
              (game_mode) ? char_F :                   
              (game_over_mode) ? (
                  p1_wins ? char_P :                   
                  p2_wins ? char_P :                   
                  char_E                               
              ) : 7'h7F;
//=======================================================
//  Structural coding
//=======================================================

endmodule